package learn2;

public class Exception2 {
	public static void main(String[] args) {
		
		try {
			
			int []a = {2,0};
			int b = 4;
			int c = b/a[2];
			System.out.println(c);
			
		}
		
		catch(ArithmeticException e) {
			System.out.println("산술오류");
		}
		catch(ArrayIndexOutOfBoundsException e) {
			System.out.println("산술오류");
		}
		System.out.println("예외처리 테스트");
		
		
		
	}

}
